### ISSUE TITLE
Cannot start the server

### ISSUE THREAD

**Issue by Kailang** [rohansub/mixtaped-demo#11]
```javascript
[root@instance-1 mixtaped-demo]# node server.js 
running on http://localhost:80
_http_client.js:25
      throw new Error('Unable to determine the domain name');
      ^

Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:25:13)
    at Object.exports.request (http.js:31:10)
    at Object.exports.get (http.js:35:21)
    at Object.<anonymous> (/home/github/mixtaped-demo/server.js:19:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

**Comment by Kailang** [comment]
I'll use a simpler method to reroute every http request to "https://mixtaped.tv" if I can start the https server.

**Comment by rohansub** [comment]
Oh I think I know the error. I can fix it now.

**Comment by rohansub** [comment]
Oh wait did you already fix it in the new branch you put up?

**Comment by Kailang** [comment]
I'll use a simpler method.

```javascript
	var httpApp = express();
	httpApp.all('*', function (req, res, next) {
		res.redirect('https://mixtaped.tv');
	});
	http.createServer(httpApp).listen(80);
	console.log('[mixtaped] reroute server running on http://localhost:80');
```

Simple.

```javascript
try {
	var privateKey = fs.readFileSync('/etc/letsencrypt/live/mixtaped.tv/privkey.pem'),
		certificate = fs.readFileSync('/etc/letsencrypt/live/mixtaped.tv/cert.pem');
	console.log('[mixtaped] private key\n', privateKey);
	console.log('[mixtaped] certificate\n', certificate);

	https.createServer({key: privateKey, cert: certificate}, app).listen(443);
	console.log('[mixtaped] server running on https://localhost:443');

	var httpApp = express();
	httpApp.all('*', function (req, res, next) {
		res.redirect('https://mixtaped.tv');
	});
	http.createServer(httpApp).listen(80);
	console.log('[mixtaped] reroute server running on http://localhost:80');
} catch (err) {
	console.log('[mixtaped] cannot start https server\n', err);

	// Local development;
	http.createServer(app).listen(8090);
	console.log('[mixtaped] server running on http://localhost:8090');
}
```
If we cannot start https, we start http://localhost:8090

**Comment by rohansub** [comment]
Change the redirect to this:
`res.redirect('https://' + req.hostname + req.url);`
It's a little cleaner if we want to change the url later. (It also has nothing to do with the earlier bug in code that was there, that was only because I forgot to comment a piece of code out)

**Comment by Kailang** [comment]
Pushed to iss11.
